name: 'Restore reports'
description: 'Restore the index.json file and tool-specific reports'

inputs:
  tool:
    description: 'The tool for which to restore reports (e.g. biapy, bioimageio.core, careamics, ilastik)'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      name: checkout staged index and existing ${{ inputs.tool }} reports
      with:
        ref: stage-gh-pages
        path: gh-pages
        sparse-checkout: |
          reports
          index.json
    - run: mv gh-pages/index.json ./index.json
      shell: bash
    - name: move tool-specific reports
      run: |
        import os
        from pathlib import Path
        from fnmatch import fnmatch

        print("cwd:", Path().resolve())
        src = Path("gh-pages/reports")
        assert src.exists(), f"Source path {src} does not exist"
        tgt = Path("reports")
        count = 0
        skip = os.environ.get("RECOMPUTE_REPORTS_PATTERN", "")
        for p_src in src.glob("**/${{inputs.tool}}_*.json"):
            if skip and fnmatch(p_src.name, skip):
               print("Skipping", p_src)
                continue
            p_tgt = tgt / p_src.relative_to(src)
            p_tgt.parent.mkdir(parents=True, exist_ok=True)
            p_src.rename(p_tgt)
            count += 1

        print("Restored", count, "reports")

      shell: python
