name: 'Restore reports'
description: 'Restore the index.json file and tool-specific reports'

inputs:
  tool:
    description: 'The tool for which to restore reports (e.g. biapy, bioimageio_core, careamics, ilastik)'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      name: checkout index and existing ${{ inputs.tool }} reports
      with:
        ref: gh-pages
        path: gh-pages
        sparse-checkout: |
          reports
          index.json
    - run: mv gh-pages/index.json ./index.json
      shell: bash
    # - run: mv gh-pages/reports/ ./reports/
    #   shell: bash
    # - run: |
    #     shopt -s globstar
    #     rm -f ! (reports/**/${{ inputs.tool }}_*.json)
    #   shell: bash
    - name: move tool-specific reports
      run: |
        from pathlib import Path

        src = Path("gh-pages/reports")
        tgt = Path("reports")
        for p_src in src.glob(f"**/{inputs.tool}_*.json"):
            p_tgt = tgt / p_src.relative_to(src)
            p_tgt.parent.mkdir(parents=True, exist_ok=True)
            p_src.rename(p_tgt)

      shell: python
