name: backup
run-name: backup

on:
  workflow_run:
    workflows: [publish]
    types: [completed]
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * 1

concurrency: backup

jobs:
  call:
    strategy:
      fail-fast: false
      matrix:
        environment_name: [production, sandbox]
    uses: bioimage-io/collection/.github/workflows/backup_call.yaml@main
    with:
      environment_name: ${{matrix.environment_name}}
    secrets: inherit
