name: check compatibility careamics

concurrency: careamics

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/check_compatibility_careamics.yaml
      - scripts/check_compatibility_careamics.py
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *  # update compatibility once a day

jobs:
  run:
    runs-on: ubuntu-latest
    environment: 'production'
    steps:
    - uses: actions/checkout@v4
    - name: Setup careamics env
      uses: mamba-org/setup-micromamba@v1
      with:
        generate-run-shell: false
        cache-downloads: true
        environment-name: careamics
        condarc: |
          channels:
            - conda-forge
            - pytorch
        create-args: >-
          pytorch
          torchvision
          cpuonly
          python=3.10
          numpy
          pip
    - run: pip install careamics
    - name: Install backoffice
      run: pip install .
    - run: python scripts/check_compatibility_careamics.py
      env:
        S3_HOST: ${{vars.S3_HOST}}
        S3_BUCKET: ${{vars.S3_BUCKET}}
        S3_FOLDER: ${{vars.S3_FOLDER}}
        S3_ACCESS_KEY_ID: ${{secrets.S3_ACCESS_KEY_ID}}
        S3_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_ACCESS_KEY}}
        RUN_URL: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
    - name: Deploy to gh-pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: reports
        dry-run: ${{ github.ref != 'refs/heads/main' }}
        target-folder: reports
        clean: false
