name: check compatibility icy

concurrency: icy

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/check_compatibility_icy.yaml
      - scripts/check_compatibility_icy/**/*
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *  # update compatibility once a day

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: bioimage-io/collection-bioimage-io
        ref: gh-pages
        path: bioimageio-gh-pages
    - name: Setup Maven Action
      uses: stCarolas/setup-maven@v4.5
      with:
        java-version: 11
        maven-version: 3.9.5
    - name: Build with Maven
      run: |
        cd scripts/check_compatibility_icy
        mvn clean install org.apache.maven.plugins:maven-shade-plugin:3.2.4:shade -Dshade.mainClass=io.bioimage.modelrunner.ci.ContinuousIntegration
    - name: Download engines
      run: |
        java -cp scripts/check_compatibility_icy/target/dl-modelrunner-ci-0.0.1-SNAPSHOT.jar io.bioimage.modelrunner.ci.DownloadEngines deepimagej
    - name: Run models
      run: |
        java -cp scripts/check_compatibility_icy/target/dl-modelrunner-ci-0.0.1-SNAPSHOT.jar io.bioimage.modelrunner.ci.ContinuousIntegration
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: test_summaries

  
  sendreport:
    runs-on: ubuntu-latest
    needs: run
    steps:
    - uses: actions/checkout@v3

    - name: Get test results
      uses: actions/upload-artifact@v3
      with:
        path: test_summaries

    - name: test with ilastik ${{ matrix.v }}
      shell: bash -l {0}
      run: python scripts/upload_reports_java.py deepimagej

