name: check compatibility icy

concurrency: icy

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/check_compatibility_icy.yaml
      - scripts/get_java_software_versions.py
      - scripts/check_compatibility_java_software/**/*
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *  # update compatibility once a day

jobs:
  generate-version-dict:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-dict.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install deps
      run: pip install requests==2.28.2 beautifulsoup4==4.12.3 packaging==23.0
    - name: Generate dict
      id: set-dict
      run: |
        matrix_output=$(python scripts/get_java_software_versions.py icy)
        echo "${matrix_output}" >> $GITHUB_ENV
        matrix=$(echo "${matrix_output}" | sed 's/matrix=//')
        echo "matrix=${matrix}" >> $GITHUB_OUTPUT
    - name: Debug matrix
      run: echo '${{ steps.set-dict.outputs.matrix }}'

  run:
    needs: generate-version-dict
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include: ${{ fromJson(needs.generate-version-dict.outputs.matrix) }}
    steps:
    - name: Debug matrix
      run: echo '${{ toJson(matrix) }}'
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: bioimage-io/collection-bioimage-io
        ref: gh-pages
        path: bioimageio-gh-pages
    - name: Setup Maven Action
      uses: stCarolas/setup-maven@v4.5
      with:
        java-version: 11
        maven-version: 3.9.5
    - name: Build with Maven
      run: |
        cd scripts/check_compatibility_java_software
        mvn clean install org.apache.maven.plugins:maven-shade-plugin:3.2.4:shade -Dshade.mainClass=io.bioimage.modelrunner.ci.ContinuousIntegration
    - name: Download engines
      run: |
        java -cp scripts/check_compatibility_java_software/target/dl-modelrunner-ci-0.0.1-SNAPSHOT.jar io.bioimage.modelrunner.ci.DownloadEngines icy
    - name: Run models
      run: |
        java -cp scripts/check_compatibility_java_software/target/dl-modelrunner-ci-0.0.1-SNAPSHOT.jar io.bioimage.modelrunner.ci.ContinuousIntegration icy "${{ matrix.key }}"
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: test_summaries

  sendreport:
    runs-on: ubuntu-latest
    needs: run
    steps:
    - uses: actions/checkout@v3
    - name: Get test results
      uses: actions/download-artifact@v3
      with:
        path: test_summaries
    - name: test with Java software ${{ matrix.v }}
      shell: bash -l {0}
      run: python scripts/check_compatibility_java_software.py icy 3.0.1 test_summaries/artifact
