name: conflate summaries

on:
  workflow_call:
  workflow_dispatch:
  workflow_run:
    workflows:
      - 'check compatibility biapy'
      - 'check compatibility careamics'
      - 'check compatibility ilastik'
    types: [completed]
    branches: [main]

concurrency: conflate-summaries


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: "pip" # caching pip dependencies
      - run: pip install .
      - run: backoffice summarize
        env:
          RUN_URL: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
