# for now we do not want any emails forwarded to the chat system
name: forward emails to chat

on:
  workflow_call:
    inputs:
      sandbox:
        description: use sandbox
        required: false
        default: true
        type: boolean
  # schedule:
  #   - cron: "0 * * * *" # every hour at minute 0

concurrency: forward-emails-to-chat


jobs:
  run:
    runs-on: ubuntu-latest
    # environment: ${{inputs.sandbox && 'sandbox' || 'production'}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: "pip"
      - run: pip install .
      - run: backoffice forward_emails_to_chat
        env:
          S3_HOST: ${{vars.S3_HOST}}
          S3_BUCKET: ${{vars.S3_BUCKET}}
          S3_FOLDER: ${{vars.S3_FOLDER}}
          S3_ACCESS_KEY_ID: ${{secrets.S3_ACCESS_KEY_ID}}
          S3_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_ACCESS_KEY}}
          MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
          BIOIMAGEIO_USER_ID: github|${{github.actor_id}}
