name: stage
run-name: stage ${{inputs.resource_id}}

on:
  workflow_dispatch:
    inputs:
      resource_id:
        description: "bioimage.io resource concept ID (e.g. 'affable-shark')"
        required: true
        type: string
      package_url:
        description: "Download URL of the resource package zip-file"
        required: true
        type: string
      sandbox:
        description: Stage to sandbox
        required: false
        default: false
        type: boolean

concurrency: ${{inputs.sandbox}}-${{inputs.resource_id}}

jobs:
  stage:
    uses: bioimage-io/collection/.github/workflows/stage_call.yaml@main
    with:
      concept_id: ${{inputs.resource_id}}
      package_url: ${{inputs.package_url}}
      environment_name: ${{inputs.sandbox && 'sandbox' || 'production'}}
    secrets: inherit

  dispatch-test:
    runs-on: ubuntu-latest
    needs: stage
    steps:
    - uses: actions/checkout@v4
    - run: |
        gh workflow run test.yaml \
          -f resource_id=${{inputs.resource_id}} \
          -f version=${{inputs.version}} \
          -f sandbox=${{inputs.sandbox}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
