name: conflate compatibility summaries

on:
  workflow_call:
  workflow_dispatch:
  workflow_run:
    workflows:
      - 'check compatibility'
    types: [completed]
    branches: [main]

concurrency: conflate-summaries


jobs:
  run:
    runs-on: ubuntu-latest
    environment: 'production'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          sparse-checkout: |
            reports
      - uses: actions/setup-python@v6
        with:
          cache: "pip"
      - run: pip install .
      - uses: ./.github/actions/cache_index
        with:
          HYPHA_API_TOKEN: ${{secrets.HYPHA_API_TOKEN}}
      - run: backoffice summarize
        env:
          RUN_URL: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
          HYPHA_API_TOKEN: ${{secrets.HYPHA_API_TOKEN}}
          REPORTS: gh-pages/reports
      - name: Deploy to gh-pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gh-pages/reports
          dry-run: ${{ github.ref != 'refs/heads/main' }}
          target-folder: reports
          clean: false
